version: "3"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - WEBUI_PORT=9091
    volumes:
      - /home/tharding/Docker/qbittorrent/config:/config
      - /home/tharding/Docker/qbittorrent/local:/.local
      - /media/data/Downloads:/Downloads
      - /media/data/Plex-Media:/Plex-Media
    network_mode: "container:gluetun_vpn" #change gluetun to your VPN container   

    restart: unless-stopped