services:
  windrose:
    image: indifferentbroccoli/windrose-server-docker
    container_name: windrose
    restart: unless-stopped
    stop_grace_period: 30s
    env_file:
      - ~/Docker/windrose/.env
    volumes:
      - ~/Docker/windrose/server-files:/home/steam/server-files
    labels:
      - "dockhand.update=false"