services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    group_add:
      - "989"
    volumes:
      - /media/data/configs/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
      PGID: ${PGID}
      PUID: ${PUID}
      HOMEPAGE_VAR_QBIT_USER: ${HOMEPAGE_VAR_QBIT_USER}
      HOMEPAGE_VAR_QBIT_PASS: ${HOMEPAGE_VAR_QBIT_PASS}
      HOMEPAGE_VAR_PORTAINER_KEY: ${HOMEPAGE_VAR_PORTAINER_KEY}
      HOMEPAGE_VAR_PLEX_TOKEN: ${HOMEPAGE_VAR_PLEX_TOKEN}
      HOMEPAGE_VAR_ADGUARD_PASS: ${HOMEPAGE_VAR_ADGUARD_PASS}
      HOMEPAGE_VAR_ADGUARD_USER: ${HOMEPAGE_VAR_ADGUARD_USER}
      
      HOMEPAGE_OIDC_ISSUER: "${AUTHENTIK_BASE_URL}/application/o/homepage/"
      HOMEPAGE_OIDC_CLIENT_ID: "${AUTHENTIK_CLIENT_ID}"
      HOMEPAGE_OIDC_CLIENT_SECRET: "${AUTHENTIK_CLIENT_SECRET}"
      
      HOMEPAGE_OIDC_NAME: "Authentik"
      HOMEPAGE_OIDC_SCOPE: "openid email profile"
