services:
  caddy:
    image: caddybuilds/caddy-cloudflare:latest
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /media/data/configs/caddy/conf/Caddyfile:/etc/caddy/Caddyfile
      - /media/data/configs/caddy/data:/data
      - /media/data/configs/caddy/config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - ACME_EMAIL=${ACME_EMAIL}
    network_mode: host
volumes:
  caddy_data:
    external: true
  caddy_config:
    
