services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    container_name: authentik-postgresql
    restart: unless-stopped

    environment:
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - /media/data/configs/authentik/postgres:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d authentik -U authentik"
        ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

    networks:
      - authentik


  server:
    image: ghcr.io/goauthentik/server:2026.6
    container_name: authentik-server
    restart: unless-stopped

    command: server

    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}

      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}

      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"

    volumes:
      - /media/data/configs/authentik/media:/data
      - /media/data/configs/authentik/templates:/templates

    ports:
      - "9000:9000"

    depends_on:
      postgresql:
        condition: service_healthy

    networks:
      - authentik


  worker:
    image: ghcr.io/goauthentik/server:2026.6
    container_name: authentik-worker
    restart: unless-stopped

    command: worker

    environment:
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}

      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}

      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"

    volumes:
      - /media/data/configs/authentik/media:/data
      - /media/data/configs/authentik/templates:/templates

      # Required for Authentik-managed Docker outposts.
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      postgresql:
        condition: service_healthy

    networks:
      - authentik


networks:
  authentik:
    name: authentik
