version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports: #make sure to include these for qbittorrent to work
      - 60000:60000
      - 60000:60000/udp
      - 9091:9091      
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=${SERVER_CITIES}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
    volumes:
      - /home/tharding/Docker/Gluetun:/gluetun
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      
  qbittorrent:
    image: linuxserver/qbittorrent:5.1.4
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - WEBUI_PORT=9091
    volumes:
      - /home/tharding/Docker/qbittorrent/config:/config
      - /home/tharding/Docker/qbittorrent/local:/.local
      - /media/data/Downloads:/Downloads
      - /media/data/Plex-Media:/Plex-Media
    network_mode: "service:gluetun" #change gluetun to your VPN container   

    restart: unless-stopped